#端口配置
server:
  port: 8082

#配置日志
logging:
  level:
    org.springfromework.web: info
    org.hibernate: error
    com.lijun: info

#数据库配置
spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.139:3306/test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root

#mybatis配置
mybatis:
  type-aliases-package: com.lijun.**.entity
  mapper-locations: classpath:mybatis/test/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

